#!/bin/bash
#ffmpeg -f pulse -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor -f x11grab -framerate 30 -video_size 1366x760 -i :0.0 -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict -2 -g 120 -f flv test.fly
 #ffmpeg -f pulse -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor -f x11grab -framerate 30 -video_size 1366x760 -i :0.0 -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict -2 -g 120 -f flv video.fly #rtmp://a.rtmp.youtube.com/live2/jgsh-wgdg-grag-09xb-1ywk
 #jgsh-wgdg-grag-09xb-1ywk

 #ffmpeg -f pulse -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor -f x11grab -framerate 30 -video_size 650x768 -i :0.0+45 -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict -2 -g 120 -f flv -y video2.fly
 
# Run the ffmpeg command with the modified file path
#ffmpeg -hide_banner -f pulse -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor -f x11grab -framerate 30 -video_size 650x768 -i :0.0+45 -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict -2 -g 120 -f flv -y "$file"

filef="/home/jack/Desktop/captures/$(date +%Y-%m-%d_%H-%M-%S)video.fly"
file="/home/jack/Desktop/captures/$(date +%Y-%m-%d_%H-%M-%S)video.mp4"
echo $file
#ffmpeg -hide_banner -f pulse -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor -f x11grab -framerate 24 -video_size 1366x718 -i :0.0+0,50 -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict -2 -g 120 -f flv -y $file

# WORKS WARNINGS: ffmpeg -hide_banner -f alsa -i plughw:0 -f x11grab -framerate 24 -video_size 1366x718 -i :0.0+0,50 -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict -2 -g 120 -f flv -y $file

#CAPTURES NO SOUND 
#ffmpeg -hide_banner -f alsa -i plughw:0 -f x11grab -framerate 24 -video_size 1366x718 -i :0.0+0,50 -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict -2 -b:a 192k -g 120 -movflags +faststart -y $file

# no ffmpeg -f alsa -i hw:PCH,0 -t 20 -ac 2 -ar 44100 -fflags +genpts -f x11grab -framerate 30 -video_size 1366x718 -i :0.0+0,50 -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict -2 -g 120 -f flv -y $file
 

#CAPTURES NO SOUND stutters
#ffmpeg -f x11grab -framerate 24 -video_size 1366x718 -i :0.0+0,50 -f pulse -i default -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict experimental -b:a 192k -g 120 -f flv -y $file
 
#ffmpeg -f pulse -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor -f x11grab -framerate 30 -video_size 650x768 -i :0.0+45 -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict -2 -g 120 -f flv -y $filef


#file="/home/jack/Desktop/captures/$(date +%Y-%m-%d_%H-%M-%S)video.mp4"
#echo $file

# working good 
#ffmpeg -hide_banner -f pulse -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor -f x11grab -framerate 30 -video_size 506x768 -i :0.0 -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict -2 -g 120 -f flv -y "$file"

# working good 
file="/home/jack/Desktop/captures/$(date +%Y-%m-%d_%H-%M-%S)video.mp4"
echo $file
#ffmpeg -hide_banner -f pulse -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor -f x11grab -framerate 30 -video_size 1366x768 -i :0.0 -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -strict -2 -g 120 -f flv -y "$file"


ffmpeg -hide_banner \
-f pulse -i alsa_input.pci-0000_00_1b.0.analog-stereo \
-f x11grab -framerate 30 -video_size 1366x768 -i :0.0 \
-c:v libx264 -preset ultrafast -pix_fmt yuv420p \
-c:a aac -strict -2 -g 120 \
-y /home/jack/Desktop/captures/$(date +%Y-%m-%d_%H-%M-%S)_mic_record.mp4
